#!/usr/bin/env bash
# installing nginx web server
apt update -y
apt install nginx -y
touch index.html
echo "Hello World" > index.html
chmod 0644 index.html
mv index.html /var/www/html
service nginx restart
