#!/usr/bin/env bash
# installing nginx web server
apt update -y
apt install nginx -y
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
redrect="\tlocation /redirect_me {\n\t\treturn 301 https:\/\/www.example.com\/new-page;\n\t}"
sed -r -i "/^\s+server_name .+;/a\ $redrect" /etc/nginx/sites-available/default
service nginx restart
