#!/usr/bin/env bash
# Installing load balancer and configures
apt-get update
apt-get install --no-install-recommends software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-2.5 -y
apt-get install haproxy=2.5.\* -y
echo -e "\nENABLED=1" >> /etc/default/haproxy
config="frontend http
        bind *:80
        mode http
        default_backend web-servers
backend web-servers
        balance roundrobin
        mode http
        server 626-web-01 34.139.7.21:80
        server 626-web-02 18.207.134.95:80"

echo -e "$config" >> /etc/haproxy/haproxy.cfg
service haproxy restart
