#!/usr/bin/env bash
# Debugging nginx installation to listen to port 80
service nginx stop
rm /etc/nginx/sites-enabled/default
ls -sfn /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
