#!/usr/bin/env bash
# bash script displays "Best School" 10 times with "Hi" after 9th position
i="0"
while [ $i -lt 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	i=$((i+1))
	done

