#!/usr/bin/env bash
# Bash script gives information about the school file
fille="./school"
if [ -e "$fille" ]
then
	echo "school file exists"
	if [ -s "$fille" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$fille" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi

