#!/usr/bin/env bash
# Configure nginx to run as nginx user including the master process
sed -i "s/listen 80 default_server;/listen 8080 default_server;/g" /etc/nginx/sites-available/default
sed -i "s/listen \[::\]:80 default_server ipv6only=on;/listen \[::\]:8080 default_server ipv6only=on;/g" /etc/nginx/sites-available/default
sed -i "s/www-data/nginx/g" /etc/nginx/nginx.conf
chown -R nginx:nginx /etc/nginx/nginx.conf
chmod -R u+r /etc/nginx/nginx.conf
chown -R nginx:nginx /var/log/nginx
chown -R nginx:nginx /run/
chmod -R u+w /var/log/nginx
chmod -R u+w /run/
pkill nginx
sudo -u nginx service nginx start

